version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vietnam_chain
      - POSTGRES_PASSWORD=vietnam_chain
      - POSTGRES_DB=vietnam_chain
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vietnam_chain -d vietnam_chain"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: