version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    volumes:
      - ./back-end/storage:/app/storage
      - ./back-end/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=7070
      - APP_NAME=blockchain-logistics-traceability
      - STORAGE_PATH=./storage
      - JWT_SECRET=your-secret-key-here-change-in-production
      - JWT_EXPIRES_IN=24h
      - BLOCKCHAIN_ENABLED=false
      - SHARDING_ENABLED=false
      - BRIDGE_ENABLED=false
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - logistics-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - logistics-network

networks:
  logistics-network:
    driver: bridge

volumes:
  mongodb_data:
